server:
  port: 9000
spring:
  application:
    name: 00-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: service-provider01
          uri: lb://service-provider01
          filters:
            - StripPrefix=1
          predicates:
            - Path=/member/**
      discovery:
        locator:
          enabled: true

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"