server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
      datasource:
        ds:
          nacos:
            ### nacos连接地址
            server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
            ## nacos连接的分组
            group-id: DEFAULT_GROUP
            ###路由存储规则
            rule-type: flow
            ### 读取配置文件的 data-id
            data-id: order-sentinel
            ###  读取培训文件类型为json
            data-type: json
  application:
    name: service-provider01

feign:
  sentinel:
    enabled: true

# 允许 Endpoints 的访问
management:
  endpoints:
    web:
      exposure:
        include: "*"

edianzu:
  companyName: 北京华清科技有限公司
  phone: 15313173701